# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-2904e53f-1f63-461d-b9ac-7d18717c053d";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-2904e53f-1f63-461d-b9ac-7d18717c053d".device = "/dev/disk/by-uuid/2904e53f-1f63-461d-b9ac-7d18717c053d";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-db695cfa-7323-48d7-934a-a205e7f5bb2f";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-db695cfa-7323-48d7-934a-a205e7f5bb2f".device = "/dev/disk/by-uuid/db695cfa-7323-48d7-934a-a205e7f5bb2f";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F73B-1188";
      fsType = "vfat";
      options = [ "fmask=0000" "dmask=0000" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
